In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("C:/Users/pande/Dropbox/Yuvaintern_week1/data/Delivery_Logistics.csv")

In [7]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [8]:
df.shape

(25000, 15)

In [10]:
df.columns.tolist()

['delivery_id',
 'delivery_partner',
 'package_type',
 'vehicle_type',
 'delivery_mode',
 'region',
 'weather_condition',
 'distance_km',
 'package_weight_kg',
 'delivery_time_hours',
 'expected_time_hours',
 'delayed',
 'delivery_status',
 'delivery_rating',
 'delivery_cost']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  float64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  object
 10  expected_time_hours  25000 non-null  object
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
dtypes: float64(4), int64(1), object(10)
memory usage: 2.9+ MB

In [12]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe(include="all")

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
count,25000.000000,25000,25000,25000,25000,25000,25000,25000.000000,25000.000000,25000,25000,25000,25000,25000.000000,25000.000000
unique,NaN,9,9,6,4,5,6,NaN,NaN,20,9,2,3,NaN,NaN
top,NaN,xpressbees,fragile items,ev bike,two day,west,foggy,NaN,NaN,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000016,no,delivered,NaN,NaN
freq,NaN,2826,2848,4218,6302,5095,4219,NaN,NaN,3118,6302,18331,18331,NaN,NaN
mean,12500.500000,NaN,NaN,NaN,NaN,NaN,NaN,150.390436,25.145898,NaN,NaN,NaN,NaN,3.666000,864.944579
std,7212.732314,NaN,NaN,NaN,NaN,NaN,NaN,86.409745,14.368663,NaN,NaN,NaN,NaN,1.149964,435.712593
min,250.990000,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,0.670000,NaN,NaN,NaN,NaN,1.000000,95.667400
25%,6250.750000,NaN,NaN,NaN,NaN,NaN,NaN,75.900000,12.680000,NaN,NaN,NaN,NaN,3.000000,490.800000
50%,12500.500000,NaN,NaN,NaN,NaN,NaN,NaN,151.000000,25.145000,NaN,NaN,NaN,NaN,4.000000,867.535000
75%,18750.250000,NaN,NaN,NaN,NaN,NaN,NaN,224.900000,37.660000,NaN,NaN,NaN,NaN,5.000000,1237.910000
max,24750.010000,NaN,NaN,NaN,NaN,NaN,NaN,297.100000,49.520000,NaN,NaN,NaN,NaN,5.000000,1632.720600

In [15]:
df["delivery_id"].head(20)

0     250.99
1     250.99
2     250.99
3     250.99
4     250.99
5     250.99
6     250.99
7     250.99
8     250.99
9     250.99
10    250.99
11    250.99
12    250.99
13    250.99
14    250.99
15    250.99
16    250.99
17    250.99
18    250.99
19    250.99
Name: delivery_id, dtype: float64

In [16]:
df["delivery_id"].nunique()

24502

In [17]:
df["delivery_id"].value_counts().head(10)

delivery_id
250.99      250
24750.01    250
24736.00      1
24735.00      1
256.00        1
251.00        1
24720.00      1
24721.00      1
24722.00      1
24723.00      1
Name: count, dtype: int64

In [18]:
df["delivery_time_hours"].value_counts().head(20)

delivery_time_hours
1970-01-01 00:00:00.000000006    3118
1970-01-01 00:00:00.000000005    3011
1970-01-01 00:00:00.000000007    2921
1970-01-01 00:00:00.000000004    2571
1970-01-01 00:00:00.000000008    2386
1970-01-01 00:00:00.000000003    2352
1970-01-01 00:00:00.000000009    1875
1970-01-01 00:00:00.000000002    1668
1970-01-01 00:00:00.000000010    1371
1970-01-01 00:00:00.000000011    1039
1970-01-01 00:00:00.000000001     963
1970-01-01 00:00:00.000000012     649
1970-01-01 00:00:00.000000013     371
1970-01-01 00:00:00.000000000     255
1970-01-01 00:00:00.000000014     247
1970-01-01 00:00:00.000000015     116
1970-01-01 00:00:00.000000016      51
1970-01-01 00:00:00.000000017      26
1970-01-01 00:00:00.000000018       7
1970-01-01 00:00:00.000000019       3
Name: count, dtype: int64

In [19]:
df["expected_time_hours"].value_counts().head(20)

expected_time_hours
1970-01-01 00:00:00.000000016    6302
1970-01-01 00:00:00.000000008    6287
1970-01-01 00:00:00.000000024    6186
1970-01-01 00:00:00.000000005    1080
1970-01-01 00:00:00.000000007    1051
1970-01-01 00:00:00.000000004    1037
1970-01-01 00:00:00.000000003    1029
1970-01-01 00:00:00.000000002    1015
1970-01-01 00:00:00.000000006    1013
Name: count, dtype: int64

In [20]:
df[df["delivery_id"] == 250.99].head(10)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600
5,250.99,amazon logistics,documents,ev bike,express,west,rainy,48.4,33.15,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000002,yes,delayed,3,391.4500
6,250.99,delhivery,groceries,scooter,same day,central,clear,198.3,43.79,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1222.8700
7,250.99,xpressbees,fragile items,van,same day,north,cold,114.6,42.63,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000008,no,delivered,3,800.8900
8,250.99,blue dart,clothing,van,same day,south,hot,142.4,14.06,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000008,no,delivered,5,854.1800
9,250.99,delhivery,pharmacy,truck,same day,east,foggy,47.1,29.28,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000008,no,delivered,5,423.3400

In [21]:
df[df["delivery_id"] == 24750.01].head(10)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
24750,24750.01,ekart,cosmetics,scooter,two day,east,rainy,194.0,9.87,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000016,no,delivered,4,999.61
24751,24750.01,blue dart,automobile parts,scooter,standard,north,clear,161.8,35.01,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000024,no,delivered,4,914.03
24752,24750.01,blue dart,cosmetics,ev bike,express,west,clear,230.0,46.65,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000006,yes,delayed,3,1339.95
24753,24750.01,delhivery,electronics,van,same day,west,cold,267.4,45.05,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000008,no,delivered,5,1572.15
24754,24750.01,fedex,documents,van,express,north,clear,67.2,37.45,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,4,498.35
24755,24750.01,amazon logistics,furniture,scooter,standard,east,cold,108.1,34.63,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000024,no,delivered,4,644.39
24756,24750.01,ekart,documents,bike,two day,south,hot,91.3,44.93,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000016,no,delivered,5,591.29
24757,24750.01,amazon logistics,automobile parts,ev van,two day,east,stormy,51.4,10.39,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000016,no,delivered,4,288.17
24758,24750.01,fedex,furniture,bike,same day,west,clear,166.6,32.53,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,5,1030.59
24759,24750.01,ekart,clothing,bike,same day,south,cold,43.6,11.10,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000008,no,delivered,4,351.30

In [22]:
df["delivery_time_hours"].head(20).tolist()

['1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000002',
 '1970-01-01 00:00:00.000000010',
 '1970-01-01 00:00:00.000000006',
 '1970-01-01 00:00:00.000000009',
 '1970-01-01 00:00:00.000000004',
 '1970-01-01 00:00:00.000000006',
 '1970-01-01 00:00:00.000000004',
 '1970-01-01 00:00:00.000000005',
 '1970-01-01 00:00:00.000000003',
 '1970-01-01 00:00:00.000000005',
 '1970-01-01 00:00:00.000000003',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000006',
 '1970-01-01 00:00:00.000000012',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000010',
 '1970-01-01 00:00:00.000000011',
 '1970-01-01 00:00:00.000000004',
 '1970-01-01 00:00:00.000000007']

In [23]:
df["expected_time_hours"].head(20).tolist()

['1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000003',
 '1970-01-01 00:00:00.000000016',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000016',
 '1970-01-01 00:00:00.000000002',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000016',
 '1970-01-01 00:00:00.000000016',
 '1970-01-01 00:00:00.000000002',
 '1970-01-01 00:00:00.000000016',
 '1970-01-01 00:00:00.000000006',
 '1970-01-01 00:00:00.000000024',
 '1970-01-01 00:00:00.000000024',
 '1970-01-01 00:00:00.000000008',
 '1970-01-01 00:00:00.000000003']

In [24]:
df[["delivery_time_hours", "expected_time_hours", "delayed"]].head(20)

              delivery_time_hours            expected_time_hours delayed
0   1970-01-01 00:00:00.000000008  1970-01-01 00:00:00.000000008      no
1   1970-01-01 00:00:00.000000002  1970-01-01 00:00:00.000000003      no
2   1970-01-01 00:00:00.000000010  1970-01-01 00:00:00.000000016      no
3   1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008      no
4   1970-01-01 00:00:00.000000009  1970-01-01 00:00:00.000000016      no
5   1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000002     yes
6   1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008      no
7   1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000008      no
8   1970-01-01 00:00:00.000000005  1970-01-01 00:00:00.000000008      no
9   1970-01-01 00:00:00.000000003  1970-01-01 00:00:00.000000008      no
10  1970-01-01 00:00:00.000000005  1970-01-01 00:00:00.000000008      no
11  1970-01-01 00:00:00.000000003  1970-01-01 00:00:00.000000016      no
12  1970-01-01 00:00:00.000000008  1970-01-01 00:00:00.000000016      no
13  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000002     yes
14  1970-01-01 00:00:00.000000012  1970-01-01 00:00:00.000000016      no
15  1970-01-01 00:00:00.000000008  1970-01-01 00:00:00.000000006     yes
16  1970-01-01 00:00:00.000000010  1970-01-01 00:00:00.000000024      no
17  1970-01-01 00:00:00.000000011  1970-01-01 00:00:00.000000024      no
18  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000008      no
19  1970-01-01 00:00:00.000000007  1970-01-01 00:00:00.000000003     yes

In [25]:
df["delayed"].value_counts(dropna=False)

delayed
no     18331
yes     6669
Name: count, dtype: int64

In [26]:
df["delivery_status"].value_counts(dropna=False)

delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [27]:
# Convert the timestamp-looking values into actual numeric values

for col in ["delivery_time_hours", "expected_time_hours"]:
    temp = pd.to_datetime(df[col], errors="coerce")
    df[col + "_clean"] = (temp - pd.Timestamp("1970-01-01")).astype("timedelta64[ns]").astype("int64")

df[[
    "delivery_time_hours",
    "delivery_time_hours_clean",
    "expected_time_hours",
    "expected_time_hours_clean"
]].head(20)

,delivery_time_hours,delivery_time_hours_clean,expected_time_hours,expected_time_hours_clean
0,1970-01-01 00:00:00.000000008,8,1970-01-01 00:00:00.000000008,8
1,1970-01-01 00:00:00.000000002,2,1970-01-01 00:00:00.000000003,3
2,1970-01-01 00:00:00.000000010,10,1970-01-01 00:00:00.000000016,16
3,1970-01-01 00:00:00.000000006,6,1970-01-01 00:00:00.000000008,8
4,1970-01-01 00:00:00.000000009,9,1970-01-01 00:00:00.000000016,16
5,1970-01-01 00:00:00.000000004,4,1970-01-01 00:00:00.000000002,2
6,1970-01-01 00:00:00.000000006,6,1970-01-01 00:00:00.000000008,8
7,1970-01-01 00:00:00.000000004,4,1970-01-01 00:00:00.000000008,8
8,1970-01-01 00:00:00.000000005,5,1970-01-01 00:00:00.000000008,8
9,1970-01-01 00:00:00.000000003,3,1970-01-01 00:00:00.000000008,8
10,1970-01-01 00:00:00.000000005,5,1970-01-01 00:00:00.000000008,8
11,1970-01-01 00:00:00.000000003,3,1970-01-01 00:00:00.000000016,16
12,1970-01-01 00:00:00.000000008,8,1970-01-01 00:00:00.000000016,16
13,1970-01-01 00:00:00.000000006,6,1970-01-01 00:00:00.000000002,2
14,1970-01-01 00:00:00.000000012,12,1970-01-01 00:00:00.000000016,16
15,1970-01-01 00:00:00.000000008,8,1970-01-01 00:00:00.000000006,6
16,1970-01-01 00:00:00.000000010,10,1970-01-01 00:00:00.000000024,24
17,1970-01-01 00:00:00.000000011,11,1970-01-01 00:00:00.000000024,24
18,1970-01-01 00:00:00.000000004,4,1970-01-01 00:00:00.000000008,8
19,1970-01-01 00:00:00.000000007,7,1970-01-01 00:00:00.000000003,3

In [28]:
df["delivery_time_hours"] = df["delivery_time_hours_clean"]
df["expected_time_hours"] = df["expected_time_hours_clean"]

df = df.drop(columns=[
    "delivery_time_hours_clean",
    "expected_time_hours_clean"
])

df[[
    "delivery_time_hours",
    "expected_time_hours"
]].head(20)

    delivery_time_hours  expected_time_hours
0                     8                    8
1                     2                    3
2                    10                   16
3                     6                    8
4                     9                   16
5                     4                    2
6                     6                    8
7                     4                    8
8                     5                    8
9                     3                    8
10                    5                    8
11                    3                   16
12                    8                   16
13                    6                    2
14                   12                   16
15                    8                    6
16                   10                   24
17                   11                   24
18                    4                    8
19                    7                    3

In [29]:
df[["delivery_time_hours", "expected_time_hours"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_time_hours  25000 non-null  int64
 1   expected_time_hours  25000 non-null  int64
dtypes: int64(2)
memory usage: 390.8 KB

In [30]:
print("Total rows:", len(df))

print("Delivery time range:",
      df["delivery_time_hours"].min(),
      "to",
      df["delivery_time_hours"].max())

print("Expected time range:",
      df["expected_time_hours"].min(),
      "to",
      df["expected_time_hours"].max())

Total rows: 25000
Delivery time range: 0 to 19
Expected time range: 2 to 24

In [31]:
df[["delivery_time_hours", "expected_time_hours"]].isnull().sum()

delivery_time_hours    0
expected_time_hours    0
dtype: int64

In [32]:
df["delivery_time_hours"].value_counts().sort_index()

delivery_time_hours
0      255
1      963
2     1668
3     2352
4     2571
5     3011
6     3118
7     2921
8     2386
9     1875
10    1371
11    1039
12     649
13     371
14     247
15     116
16      51
17      26
18       7
19       3
Name: count, dtype: int64

In [33]:
df[df["delivery_time_hours"] == 0][[
    "delivery_id",
    "delivery_partner",
    "package_type",
    "distance_km",
    "delivery_time_hours",
    "expected_time_hours",
    "delayed",
    "delivery_status",
    "delivery_cost"
]].head(20)

,delivery_id,delivery_partner,package_type,distance_km,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_cost
87,250.99,ekart,furniture,3.6,0,16,no,delivered,95.6674
136,250.99,shadowfax,groceries,8.7,0,8,no,delivered,245.2900
181,250.99,blue dart,pharmacy,9.9,0,8,no,delivered,240.2200
303,304.00,ecom express,cosmetics,21.0,0,8,no,delivered,229.0000
574,575.00,delhivery,fragile items,41.7,0,2,no,delivered,342.4100
823,824.00,shadowfax,documents,13.2,0,8,no,delivered,245.7100
836,837.00,amazon logistics,automobile parts,24.5,0,16,no,delivered,229.3300
871,872.00,blue dart,documents,33.3,0,8,no,delivered,412.0000
947,948.00,blue dart,fragile items,9.0,0,24,no,delivered,95.6674
1046,1047.00,ekart,pharmacy,10.5,0,8,no,delivered,253.3000
1060,1061.00,xpressbees,groceries,24.7,0,2,no,delivered,307.7200
1103,1104.00,blue dart,fragile items,43.0,0,2,no,delivered,389.7100
1109,1110.00,delhivery,documents,3.6,0,16,no,delivered,95.6674
1292,1293.00,dhl,furniture,20.5,0,2,no,delivered,165.7900
1528,1529.00,delhivery,cosmetics,14.4,0,16,no,delivered,115.7700
1757,1758.00,shadowfax,fragile items,19.9,0,24,no,delivered,121.5500
1773,1774.00,dhl,documents,3.6,0,2,no,delivered,124.7300
1837,1838.00,ekart,documents,3.6,0,8,no,delivered,151.7300
2165,2166.00,ecom express,pharmacy,28.4,0,24,no,delivered,291.7000
2433,2434.00,ekart,pharmacy,20.6,0,24,no,delivered,209.6800

In [34]:
df[df["delivery_time_hours"] == 0]["delivery_status"].value_counts()

delivery_status
delivered    255
Name: count, dtype: int64

In [35]:
df[df["delivery_time_hours"] == 0]["delayed"].value_counts()

delayed
no    255
Name: count, dtype: int64

In [36]:
df["expected_time_hours"].value_counts().sort_index()

expected_time_hours
2     1015
3     1029
4     1037
5     1080
6     1013
7     1051
8     6287
16    6302
24    6186
Name: count, dtype: int64

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df["delivery_id"].describe()

count    25000.000000
mean     12500.500000
std       7212.732314
min        250.990000
25%       6250.750000
50%      12500.500000
75%      18750.250000
max      24750.010000
Name: delivery_id, dtype: float64

In [39]:
df["delivery_id"].value_counts().head(15)

delivery_id
250.99      250
24750.01    250
24736.00      1
24735.00      1
256.00        1
251.00        1
24720.00      1
24721.00      1
24722.00      1
24723.00      1
24724.00      1
24725.00      1
24726.00      1
24727.00      1
24728.00      1
Name: count, dtype: int64

In [41]:
df[df["delivery_id"].isin([250.99, 24750.01])][[
    "delivery_id",
    "delivery_partner",
    "package_type",
    "vehicle_type",
    "delivery_mode",
    "region",
    "distance_km",
    "delivery_time_hours",
    "expected_time_hours",
    "delayed",
    "delivery_status"
]].head(20)

Empty DataFrame
Columns: [delivery_id, delivery_partner, package_type, vehicle_type, delivery_mode, region, distance_km, delivery_time_hours, expected_time_hours, delayed, delivery_status]
Index: []

In [42]:
print("250.99 rows:", len(df[df["delivery_id"] == 250.99]))
print("24750.01 rows:", len(df[df["delivery_id"] == 24750.01]))

250.99 rows: 0
24750.01 rows: 0

In [43]:
df.loc[
    df["delivery_id"].isin([250.99, 24750.01]),
    "delivery_id"
].value_counts()

Series([], Name: count, dtype: int64)

In [44]:
df.loc[df["delivery_id"].round(2).isin([250.99, 24750.01]), 
       "delivery_id"].head(20)

Series([], Name: delivery_id, dtype: int64)

In [45]:
df["delivery_id"].round(2).value_counts().head(15)

delivery_id
24750    251
250      250
270        1
24735      1
24734      1
255        1
253        1
24720      1
24721      1
24722      1
24723      1
24724      1
24725      1
24726      1
24727      1
Name: count, dtype: int64

In [46]:
print(df["delivery_id"].dtype)

print("250.99:", 
      df.loc[df["delivery_id"].round(2) == 250.99, "delivery_id"].iloc[0])

print("24750.01:", 
      df.loc[df["delivery_id"].round(2) == 24750.01, "delivery_id"].iloc[0])

int64

IndexError: single positional indexer is out-of-bounds

In [47]:
print(df["delivery_id"].value_counts().head(15))

delivery_id
24750    251
250      250
270        1
24735      1
24734      1
255        1
253        1
24720      1
24721      1
24722      1
24723      1
24724      1
24725      1
24726      1
24727      1
Name: count, dtype: int64

In [48]:
print(df["delivery_id"].nunique())
print(len(df))

24501
25000

In [49]:
df[df["delivery_id"].isin([250, 24750])].head(20)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206
1,250,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700
2,250,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700
3,250,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700
4,250,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600
5,250,amazon logistics,documents,ev bike,express,west,rainy,48.4,33.15,4,2,yes,delayed,3,391.4500
6,250,delhivery,groceries,scooter,same day,central,clear,198.3,43.79,6,8,no,delivered,3,1222.8700
7,250,xpressbees,fragile items,van,same day,north,cold,114.6,42.63,4,8,no,delivered,3,800.8900
8,250,blue dart,clothing,van,same day,south,hot,142.4,14.06,5,8,no,delivered,5,854.1800
9,250,delhivery,pharmacy,truck,same day,east,foggy,47.1,29.28,3,8,no,delivered,5,423.3400
10,250,fedex,groceries,scooter,same day,east,cold,293.2,22.05,5,8,no,delivered,4,1632.1500
11,250,ecom express,electronics,truck,two day,east,cold,80.4,46.48,3,16,no,delivered,5,541.4400
12,250,xpressbees,pharmacy,ev van,two day,north,rainy,257.7,20.56,8,16,no,delivered,4,1350.1800
13,250,xpressbees,cosmetics,bike,express,east,stormy,19.0,3.36,6,2,yes,failed,1,155.0800
14,250,xpressbees,automobile parts,ev bike,two day,east,stormy,237.9,24.59,12,16,no,delivered,3,1263.2700
15,250,amazon logistics,furniture,ev van,express,north,hot,239.3,11.67,8,6,yes,delayed,3,1281.5100
16,250,fedex,documents,bike,standard,west,stormy,79.0,0.73,10,24,no,delivered,5,397.1900
17,250,blue dart,fragile items,ev bike,standard,central,rainy,170.7,45.62,11,24,no,delivered,5,990.3600
18,250,amazon logistics,documents,van,same day,north,rainy,90.0,33.70,4,8,no,delivered,3,651.1000
19,250,fedex,cosmetics,truck,express,north,rainy,64.0,6.03,7,3,yes,failed,2,388.0900

In [50]:
print(df.groupby("delivery_id").size().value_counts().sort_index())

1      24499
250        1
251        1
Name: count, dtype: int64

In [51]:
print(df[df["delivery_id"].isin([250, 24750])]["delivery_id"].value_counts())

delivery_id
24750    251
250      250
Name: count, dtype: int64

In [52]:
print(df["delivery_id"].min())
print(df["delivery_id"].max())

print(df["delivery_id"].sort_values().head(20).tolist())
print(df["delivery_id"].sort_values().tail(20).tolist())

250
24750
[250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250]
[24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750, 24750]

In [53]:
print(df[df["delivery_id"].isin([250, 24750])][
    ["delivery_id", "delivery_partner", "package_type",
     "vehicle_type", "delivery_mode", "region",
     "distance_km", "delivery_cost"]
].tail(10))

       delivery_id delivery_partner      package_type vehicle_type  \
24990        24750        blue dart     fragile items         bike
24991        24750     ecom express       electronics       ev van
24992        24750        delhivery     fragile items         bike
24993        24750            fedex         groceries      scooter
24994        24750              dhl         documents         bike
24995        24750              dhl         furniture      scooter
24996        24750     ecom express  automobile parts       ev van
24997        24750            ekart          clothing      scooter
24998        24750        shadowfax         documents       ev van
24999        24750        blue dart          pharmacy      ev bike

      delivery_mode   region  distance_km  delivery_cost
24990      same day    north         40.5         322.99
24991       two day    south        244.3        1287.05
24992      same day     east        259.1        1492.19
24993       express  central        112.1         739.41
24994      same day  central        208.4        1157.30
24995       two day     east         80.7         414.45
24996      standard     west        172.9         928.76
24997      same day     east        168.4         956.55
24998      standard     west         37.2         210.12
24999       two day  central        279.3        1411.68

In [54]:
categorical_cols = [
    "delivery_partner",
    "package_type",
    "vehicle_type",
    "delivery_mode",
    "region",
    "weather_condition",
    "delayed",
    "delivery_status"
]

for col in categorical_cols:
    print("\n---", col, "---")
    print(df[col].value_counts())

--- delivery_partner ---
delivery_partner
xpressbees          2826
fedex               2818
dhl                 2802
ekart               2801
blue dart           2798
delhivery           2786
shadowfax           2736
ecom express        2722
amazon logistics    2711
Name: count, dtype: int64

--- package_type ---
package_type
fragile items       2848
pharmacy            2810
documents           2805
automobile parts    2795
electronics         2792
clothing            2767
furniture           2746
cosmetics           2744
groceries           2693
Name: count, dtype: int64

--- vehicle_type ---
vehicle_type
ev bike    4218
van        4187
scooter    4174
bike       4160
truck      4145
ev van     4116
Name: count, dtype: int64

--- delivery_mode ---
delivery_mode
two day     6302
same day    6279
express     6233
standard    6186
Name: count, dtype: int64

--- region ---
region
west       5095
central    5060
south      4977
north      4949
east       4919
Name: count, dtype: int64

--- weather_condition ---
weather_condition
foggy     4219
stormy    4198
rainy     4171
cold      4158
hot       4130
clear     4124
Name: count, dtype: int64

--- delayed ---
delayed
no     18331
yes     6669
Name: count, dtype: int64

--- delivery_status ---
delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [55]:
numeric_cols = [
    "distance_km",
    "package_weight_kg",
    "delivery_time_hours",
    "expected_time_hours",
    "delivery_rating",
    "delivery_cost"
]

print(df[numeric_cols].describe().T)

                       count        mean         std      min     25%  \
distance_km          25000.0  150.390436   86.409745   3.6000   75.90
package_weight_kg    25000.0   25.145898   14.368663   0.6700   12.68
delivery_time_hours  25000.0    6.248040    3.140935   0.0000    4.00
expected_time_hours  25000.0   13.107680    7.559024   2.0000    8.00
delivery_rating      25000.0    3.666000    1.149964   1.0000    3.00
delivery_cost        25000.0  864.944579  435.712593  95.6674  490.80

                         50%      75%        max
distance_km          151.000   224.90   297.1000
package_weight_kg     25.145    37.66    49.5200
delivery_time_hours    6.000     8.00    19.0000
expected_time_hours    8.000    16.00    24.0000
delivery_rating        4.000     5.00     5.0000
delivery_cost        867.535  1237.91  1632.7206

In [56]:
print("Negative values:")
print((df[numeric_cols] < 0).sum())

print("\nZero values:")
print((df[numeric_cols] == 0).sum())

Negative values:
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delivery_rating        0
delivery_cost          0
dtype: int64

Zero values:
distance_km              0
package_weight_kg        0
delivery_time_hours    255
expected_time_hours      0
delivery_rating          0
delivery_cost            0
dtype: int64

In [57]:
numeric_cols = [
    "distance_km",
    "package_weight_kg",
    "delivery_time_hours",
    "expected_time_hours",
    "delivery_rating",
    "delivery_cost"
]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    
    print(f"\n--- {col} ---")
    print("Lower limit:", round(lower, 2))
    print("Upper limit:", round(upper, 2))
    print("Outliers:", len(outliers))

--- distance_km ---
Lower limit: -147.6
Upper limit: 448.4
Outliers: 0

--- package_weight_kg ---
Lower limit: -24.79
Upper limit: 75.13
Outliers: 0

--- delivery_time_hours ---
Lower limit: -2.0
Upper limit: 14.0
Outliers: 203

--- expected_time_hours ---
Lower limit: -4.0
Upper limit: 28.0
Outliers: 0

--- delivery_rating ---
Lower limit: 0.0
Upper limit: 8.0
Outliers: 0

--- delivery_cost ---
Lower limit: -629.87
Upper limit: 2358.58
Outliers: 0

In [58]:
outlier_delivery_time = df[df["delivery_time_hours"] > 14]

print(outlier_delivery_time[
    [
        "delivery_time_hours",
        "expected_time_hours",
        "delayed",
        "delivery_status",
        "distance_km",
        "delivery_mode",
        "weather_condition"
    ]
].head(20))

      delivery_time_hours  expected_time_hours delayed delivery_status  \
230                    16                    8     yes         delayed
356                    15                    7     yes         delayed
415                    15                    7     yes         delayed
438                    15                   24      no       delivered
622                    15                    8     yes         delayed
778                    16                   16     yes         delayed
882                    15                   16      no       delivered
1169                   16                    8     yes         delayed
1276                   15                    7     yes         delayed
1354                   16                   16     yes         delayed
1428                   15                    7     yes         delayed
1527                   17                   24      no       delivered
1691                   16                    8     yes         delayed
1768                   16                    7     yes         delayed
1880                   17                    7     yes         delayed
2209                   15                   16      no       delivered
2260                   15                   16      no       delivered
2327                   15                    8     yes         delayed
2738                   16                   24      no       delivered
2961                   15                    7     yes          failed

      distance_km delivery_mode weather_condition
230         262.9      same day            stormy
356         293.3       express            stormy
415         270.7       express            stormy
438         267.7      standard             rainy
622         284.9      same day            stormy
778         264.4       two day            stormy
882         247.4       two day            stormy
1169        255.0      same day             rainy
1276        293.2       express            stormy
1354        261.1       two day            stormy
1428        272.5       express             rainy
1527        295.0      standard            stormy
1691        261.8      same day            stormy
1768        277.4       express             foggy
1880        276.2       express             rainy
2209        292.0       two day            stormy
2260        288.3       two day             rainy
2327        292.3      same day            stormy
2738        291.7      standard             rainy
2961        285.7       express            stormy

In [59]:
print(outlier_delivery_time["delivery_time_hours"].value_counts().sort_index())

delivery_time_hours
15    116
16     51
17     26
18      7
19      3
Name: count, dtype: int64

In [60]:
df = df[df["delivery_time_hours"] <= 14]

In [61]:
df["calculated_delayed"] = np.where(
    df["delivery_time_hours"] > df["expected_time_hours"],
    "yes",
    "no"
)

print(pd.crosstab(df["calculated_delayed"], df["delayed"]))

delayed                no   yes
calculated_delayed
no                  18256  1187
yes                     0  5354

In [62]:
df = df[df["delivery_time_hours"] <= 14]

In [64]:
for col in ["delivery_time_hours", "expected_time_hours"]:
    temp = pd.to_datetime(df[col], errors="coerce")
    df[col + "_clean"] = (
        (temp - pd.Timestamp("1970-01-01"))
        .astype("timedelta64[ns]")
        .astype("int64")
    )

df["delivery_time_hours"] = df["delivery_time_hours_clean"]
df["expected_time_hours"] = df["expected_time_hours_clean"]

df = df.drop(columns=["delivery_time_hours_clean", "expected_time_hours_clean"])

In [65]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\pande\anaconda_projects\db
['.ipynb_checkpoints', 'project_filebrowser.db', 'Week1_Data_Cleaning.ipynb']

In [67]:
import os

for root, dirs, files in os.walk(r"C:\Users\pande\anaconda_projects"):
    if "Delivery_Logistics.csv" in files:
        print(os.path.join(root, "Delivery_Logistics.csv"))

In [69]:
import os

print(os.listdir(r"C:\Users\pande"))

['.anaconda', '.antigravity-ide', '.arduinoIDE', '.cache', '.claude', '.claude.json', '.conda', '.condarc', '.continuum', '.copilot', '.cursor', '.gemini', '.git', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.local', '.matplotlib', '.redhat', '.securecoder', '.spyder-py3', '.TurboVPN', '.VirtualBox', '.vscode', 'anaconda3', 'anaconda_projects', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'Dropbox', 'Favorites', 'Jedi', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'node_modules', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{286741aa-63bb-11f0-9356-b0dcefdbad6b}.TM.blf', 'NTUSER.DAT{286741aa-63bb-11f0-9356-b0dcefdbad6b}.TM.blf.cnpf', 'NTUSER.DAT{286741aa-63bb-11f0-9356-b0dcefdbad6b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{286741aa-63bb-11f0-9356-b0dcefdbad6b}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{286741aa-63bb-11f0-9356-b0dcefdbad6b}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{286741aa-63bb-11f0-9356-b0dcefdbad6b}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'package-lock.json', 'package.json', 'Pictures', 'PrintHood', 'Projects', 'PyCharmMiscProject', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Videos', 'VirtualBox VMs']

In [70]:
print(os.listdir(r"C:\Users\pande\Dropbox"))

['.dropbox', '.dropbox.cache', 'CapCut', 'desktop.ini', 'drawing.png', 'Yuvaintern_week1']

In [71]:
df = df[df["delivery_time_hours"] <= 14]

In [72]:
print(os.listdir(r"C:\Users\pande\Dropbox\Yuvaintern_week1"))

['data', 'notebook', 'output', 'report']

In [73]:
print(os.listdir(r"C:\Users\pande\Dropbox\Yuvaintern_week1\data"))

['Delivery_Logistics.csv']

In [74]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    r"C:\Users\pande\Dropbox\Yuvaintern_week1\data\Delivery_Logistics.csv"
)

print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 25000
Columns: 15

In [75]:
df_original = df.copy()

In [76]:
df = df_original.copy()

In [77]:
for col in ["delivery_time_hours", "expected_time_hours"]:
    temp = pd.to_datetime(df[col], errors="coerce")

    df[col + "_clean"] = (
        (temp - pd.Timestamp("1970-01-01"))
        .astype("timedelta64[ns]")
        .astype("int64")
    )

df["delivery_time_hours"] = df["delivery_time_hours_clean"]
df["expected_time_hours"] = df["expected_time_hours_clean"]

df = df.drop(
    columns=["delivery_time_hours_clean", "expected_time_hours_clean"]
)

In [78]:
print(df.shape)

print(df[[
    "delivery_time_hours",
    "expected_time_hours"
]].dtypes)

(25000, 15)
delivery_time_hours    int64
expected_time_hours    int64
dtype: object

In [79]:
df["calculated_delayed"] = np.where(
    df["delivery_time_hours"] > df["expected_time_hours"],
    "yes",
    "no"
)

print(pd.crosstab(
    df["calculated_delayed"],
    df["delayed"]
))

delayed                no   yes
calculated_delayed
no                  18331  1203
yes                     0  5466

In [80]:
inconsistent_delayed = df[
    (df["delivery_time_hours"] <= df["expected_time_hours"]) &
    (df["delayed"] == "yes")
]

print("Inconsistent records:", len(inconsistent_delayed))

print(
    inconsistent_delayed[
        [
            "delivery_time_hours",
            "expected_time_hours",
            "delayed",
            "delivery_status",
            "distance_km",
            "delivery_mode",
            "weather_condition"
        ]
    ].head(20)
)

Inconsistent records: 1203
     delivery_time_hours  expected_time_hours delayed delivery_status  \
79                     3                    3     yes         delayed
80                     8                    8     yes         delayed
140                    8                    8     yes         delayed
155                    8                    8     yes         delayed
202                    3                    3     yes          failed
209                    8                    8     yes         delayed
219                    6                    6     yes         delayed
229                    2                    2     yes         delayed
239                    7                    7     yes         delayed
248                    8                    8     yes         delayed
250                    3                    3     yes          failed
264                    4                    4     yes          failed
269                    7                    7     yes          failed
277                    8                    8     yes         delayed
278                    8                    8     yes         delayed
305                    8                    8     yes         delayed
353                    8                    8     yes         delayed
459                    8                    8     yes         delayed
465                    8                    8     yes         delayed
468                    8                    8     yes          failed

     distance_km delivery_mode weather_condition
79          56.0       express               hot
80          70.7      same day            stormy
140         75.7      same day            stormy
155        146.1      same day             foggy
202         55.7       express             rainy
209        282.9      same day             clear
219        207.8       express             clear
229         36.9       express             clear
239        257.0       express             foggy
248        123.5      same day             foggy
250         74.1       express               hot
264        133.4       express             clear
269        257.8       express             rainy
277        191.2      same day            stormy
278        223.8      same day             foggy
305         70.8      same day            stormy
353        271.2      same day             clear
459        143.4      same day            stormy
465        134.6      same day             foggy
468         97.7      same day             rainy

In [81]:
print(
    inconsistent_delayed["delivery_status"].value_counts()
)

delivery_status
delayed    963
failed     240
Name: count, dtype: int64

In [83]:
print(pd.crosstab(
    df["delayed"],
    df["delivery_status"]
))

delivery_status  delayed  delivered  failed
delayed
no                     0      18331       0
yes                 5341          0    1328

In [84]:
df = df.drop(columns=["calculated_delayed"])

In [85]:
print(df.shape)
print(df.columns.tolist())

(25000, 15)
['delivery_id', 'delivery_partner', 'package_type', 'vehicle_type', 'delivery_mode', 'region', 'weather_condition', 'distance_km', 'package_weight_kg', 'delivery_time_hours', 'expected_time_hours', 'delayed', 'delivery_status', 'delivery_rating', 'delivery_cost']

In [86]:
df.dtypes

delivery_id            float64
delivery_partner        object
package_type            object
vehicle_type            object
delivery_mode           object
region                  object
weather_condition       object
distance_km            float64
package_weight_kg      float64
delivery_time_hours      int64
expected_time_hours      int64
delayed                 object
delivery_status         object
delivery_rating          int64
delivery_cost          float64
dtype: object

In [87]:
df["delivery_id"].head(10)

0    250.99
1    250.99
2    250.99
3    250.99
4    250.99
5    250.99
6    250.99
7    250.99
8    250.99
9    250.99
Name: delivery_id, dtype: float64

In [88]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
delivery_id,25000.0,12500.500000,7212.732314,250.9900,6250.75,12500.500,18750.25,24750.0100
distance_km,25000.0,150.390436,86.409745,3.6000,75.90,151.000,224.90,297.1000
package_weight_kg,25000.0,25.145898,14.368663,0.6700,12.68,25.145,37.66,49.5200
delivery_time_hours,25000.0,6.248040,3.140935,0.0000,4.00,6.000,8.00,19.0000
expected_time_hours,25000.0,13.107680,7.559024,2.0000,8.00,8.000,16.00,24.0000
delivery_rating,25000.0,3.666000,1.149964,1.0000,3.00,4.000,5.00,5.0000
delivery_cost,25000.0,864.944579,435.712593,95.6674,490.80,867.535,1237.91,1632.7206

In [89]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Negative values:", (df.select_dtypes(include="number") < 0).sum().sum())

Rows: 25000
Columns: 15
Missing values: 0
Duplicate rows: 0
Negative values: 0

In [90]:
output_path = r"C:\Users\pande\Dropbox\Yuvaintern_week1\output\Delivery_Logistics_Cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print(output_path)

Cleaned dataset saved successfully!
C:\Users\pande\Dropbox\Yuvaintern_week1\output\Delivery_Logistics_Cleaned.csv

In [91]:
df["distance_category"] = pd.cut(
    df["distance_km"],
    bins=[0, 100, 200, float("inf")],
    labels=["Short", "Medium", "Long"]
)

df["distance_category"].value_counts()

distance_category
Medium    8415
Short     8317
Long      8268
Name: count, dtype: int64

In [92]:
output_path = r"C:\Users\pande\Dropbox\Yuvaintern_week1\output\Delivery_Logistics_Cleaned.csv"

df.to_csv(output_path, index=False)

print("Updated cleaned dataset saved!")
print("Shape:", df.shape)

Updated cleaned dataset saved!
Shape: (25000, 16)